### ISSUE TITLE
Breaks on complex interpolations

### ISSUE THREAD

**Issue by mxstbr** [styled-components/stylelint-processor-styled-components#6]
Currently, this breaks on a complex interpolation:

``` JS
const background = 'background: red;';
const Button = styled.div`
  color: red;
  ${background}
`;
```

We represent this for stylelint like so:

``` CSS
.selector {
  color: red;
  $background
}
```

The problem is that, while stylelint ignores Sass variables, those cannot represent full strings, which means stylelint throws a "CssSyntaxError" on the above code eventhough it's not a syntax error at all. 😕

Any ideas what we could do here @davidtheclark?

(also related to #4)

**Comment by davidtheclark** [comment]
@mxstbr: Hm. Given the absolute flexibility of template string interpolation there is no way that this situation will not arise for some people doing wacky things. For example, you could `@med${media-last-letters} ${min-opener}-width: 40px)`. I think it's worth making some recommendations in the documentation about interpolation practices.

Another possibility is to go back to the "blur" idea. Instead of replacing with an innocuous character, though, how about replacing with a comment?

Before passing the following into stylelint ...

```css
const Button = styled.div`
  color: red;
  ${background}
`;
```

Transform it into ...

```css
const Button = styled.div`
  color: red;
  /*backgroun*/
`;
```

Notice I cut the last character of "background" to keep character count the same.

A simpler example should also work, I think.

```css
const Button = styled.div`
  color: ${color};
`;
```

To ...

```css
const Button = styled.div`
  color: /*colo*/;
`;
```

That wacky `@media` example above will still have problems.

**Comment by mxstbr** [comment]
I like that idea! Going to try that now

**Comment by Munter** [comment]
Won't this be a certain linting error? You assigned no value
```js
const Button = styled.div`
  color: /*colo*/;
`;
```

**Comment by davidtheclark** [comment]
@Munter: PostCSS parses it, so it should be fine.

**Comment by mxstbr** [comment]
Not getting a linting error on that ¯\_(ツ)_/¯ (see the `fix-interpolations` branch)

**Comment by mxstbr** [comment]
God dammit, this breaks in this case:

```JS
const Box = styled.div`
  @media (max-width: ${constants.maxWidth}) {

  }
`;
```

which gets correctly replaced and sends stylelint this CSS:

```JS
const Box = styled.div`
  @media (max-width: /*aaaaaaaaaaaaaa*/) {

  }
`;
```

But then stylelint complains

```
2:21 ✖ Unexpected whitespace before ")"   media-feature-parentheses-space-inside
```

Any ideas how we could solve this?

**Comment by davidtheclark** [comment]
That looks like it may be a bug in the rule, because there is in fact no space before that parenthesis.

**Comment by mxstbr** [comment]
Bug is now fixed in stylelint, thanks to @davidtheclark!

**Comment by esphen** [comment]
Still seeing `Unknown word: CssSyntaxError` with 0.0.4 on a simple example like this:

```javascript
import styled, { css } from 'styled-components';

const hoverStyle = css`
  background-color: gray;
  color: gray;
`;

export const StyledRequest = styled.div`
  ${hoverStyle}
`;
```

Any update?

**Comment by mxstbr** [comment]
Not yet, haven't come around to working on this again. Let me take a look at it on Monday, thanks for providing the tiny repro, much appreciated! 

If you want to look into it, you can add a new file to our test fixtures with your repo, copy some of the tests and submit a PR with the failing tests. That'd be really helpful!

**Comment by gihrig** [comment]
Short of a permanent fix, would it be possible to support style lint disable comments?

e.g.
`/* stylelint-disable-line */` 

or better still, disable single rules:
`/* stylelint-disable-line CssSyntaxError */`

**Comment by mxstbr** [comment]
That should already work I think @gihrig

**Comment by gihrig** [comment]
From RBP `component/Button/A.js`

````javascript
import styled from 'styled-components';

import buttonStyles from './buttonStyles';

const A = styled.a`${buttonStyles}`; /* stylelint-disable-line CssSyntaxError */

export default A;
````
![image](https://cloud.githubusercontent.com/assets/1481063/20935955/ad58283e-bb95-11e6-84db-2b73a886d692.png)

Also tried `/* stylelint-disable */` at top of file.

**Comment by gihrig** [comment]
Noticing that `/* stylelint-disable-line CssSyntaxError */` is outside the template literal, I also tried this:

````javascript
    ${props.rotate && `
       /* stylelint-disable CssSyntaxError */
      -webkit-transform: rotate(${props.rotate}deg);
      -ms-transform: rotate(${props.rotate}deg);
      transform: rotate(${props.rotate}deg);
    `}
````

Same result, a `CssSyntaxError`.

**Comment by mxstbr** [comment]
I think `CssSyntaxError`s can't be ignored, since they're not rule issues but parsing errors that you can't just ignore.

**Comment by gihrig** [comment]
Yeah, that makes sense. Bummer 😞

**Comment by chuanxie** [comment]
any update?

**Comment by rainydio** [comment]
@chuanxie i've made a dirty fix and created pull request #17. It isn't really fixing complex interpolations. But creates a workaround.

**Comment by chuanxie** [comment]
@rainydio awesome, at least it works. thanks a lot.  `-styled-mixin` it works
